### ISSUE TITLE
Feature request: Show the user not only that an EV3 was found, but also whether it is an ev3dev, ev3lejosv0 or ev3lejosv1

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-connector#11]
When a user connects the EV3 to the computer, the connector program only shows that an EV3 was found. 
If the connector Program could also tell the user whether or not "EV3 leJOS 0.9.0", "EV3 leJOS 0.9.1" or "EV3dev" was found, the user would directly know which robot system to pick in the Open Roberta Lab.

This feature is more or less useful for people who are quite new to the Open Roberta Lab.

**Comment by bjost2s** [comment]
Afaik the connector only can discover EV3 leJOS 0.9.0" and  "EV3 leJOS 0.9.1. As EV3 leJOS 0.9.0" is outdated I think there is no need to add this feature.

**Comment by boonto** [comment]
Then this is out of the question for now.
