### ISSUE TITLE
Improve Linux installer

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-connector#14]
The Linux install script currently creates a new su shell which leaves the user logged in as an admin and in a different folder after it finished. This is not really nice and should be changed.

**Comment by capnm** [comment]
There isn't really need to have root access, if the user is already in the `dialout` group.
Or please add a 'run.sh' script or something similar.
Thanks.

**Comment by boonto** [comment]
Thanks for the suggestion, I could add a parameter that specifies whether the user should be added to `dialout` to remove the admin requirements.

**Comment by capnm** [comment]
You could do that automatically, see e.g.:
https://stackoverflow.com/questions/18431285/check-if-a-user-is-in-a-group#29557400
