### ISSUE TITLE
Java is not found on the Mac

### ISSUE THREAD

**Issue by the-matzup** [OpenRoberta/openroberta-connector#16]
When opening the connector the following error message appears:

(translated:) "To use the java command line tool, you must install a java development package." 
(german:) "Um das java-Befehlszeilenprogramm nutzen zu können, musst du ein Java-Entwicklungspaket installieren."

If I unpack the program package manually and open OpenRobertaConnector.jar directly, everything works. The problem probably lies in the executing batch script. 

Versions:
OpenRobertaConnector: v1.2.0
installed Java-Version: 8 (Update 231)
macOS Catalina 10.15.2

**Comment by boonto** [comment]
Can you tell me the output of running `java -version` in a shell? Does it output something similar to the Java version you posted?

**Comment by the-matzup** [comment]
`java -version`: `No Java runtime present, requesting install.`

After some searching on the internet, I found the following command, which did at least something: 
`I export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"`

After entering the command:
`java -version`
`java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)`

After executing the command, I can now start OpenRobertaConnector from the bash file included in the app package.  But the funny thing is: The bash file only works if I open it via the shell, when I execute it with the mouse (double click) on the bash file, the old known error that Java was not found occurs.

(Even if at first sight it looks like it is a single problem of my computer, this problem with Java also occurs on other Macs of my other colleagues. I even did a fresh reinstallation of the operating system once to rule out that something is broken on my system.)

**Comment by boonto** [comment]
How exactly are you installing Java? Through the AppStore or downloading it from the internet and running an installer? I am not sure what the usual workflow is for macOS.

**Comment by the-matzup** [comment]
Java is performed directly via an installation routine of Java/Oracle. The installation package is downloaded directly from Java: https://www.java.com/en/download/mac_download.jsp

By the way: According to the Java homepage the command java -version only works if the full Java package is installed.

I can imagine that it is a problem of the path that leads to the error message?!?

**Comment by boonto** [comment]
Seems like it is not added to the path in that install method. What is "the full Java package"?

In order to fix this immediately you would have to add the
```
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```
to your `.bash_profile`, that way it should work (probably after a restart or relog) via the app directly.

**Comment by the-matzup** [comment]
Instead of creating a temporary/permanent solution just for me, I would like to have a solution for everyone. OpenRobertaConnector should be used by more people and should not frustrate Mac users and make them give up (or have to take a computer science degree first ;-). 

Therefore my suggestion is to write the change into the OpenRobertaConnector executable batch file. Maybe best with an if-query, so that other Java installations are not compromised:

```
#!/bin/bash
if [ -d "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents" ]; then
	export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"; fi
cd "$(dirname $BASH_SOURCE)"
cd ..
java -jar OpenRobertaConnector.jar
```

I have already changed the program file of OpenRobertaConnector accordingly and everything works.

By the way: The full Java version means JDK instead of JDE. 
Source: FAQ at Oracle : https://www.java.com/en/download/faq/java_mac.xml#yosemitejava
> "When I try to use java from the command line, why doesn't it work? I have Oracle's version of the JRE installed."
> Installing a JRE from Oracle does not update java -version symlinks or add java to your path. For this functionality, you must install the full JDK. See Mac command line info.

**Comment by boonto** [comment]
I believe this only applies for this method of installing Java (Path seems to be the same for [9](https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-5F4A0659-BFC5-4CB9-9920-D2DEABF29894), but differs for [13](https://docs.oracle.com/en/java/javase/13/install/installation-jdk-macos.html#GUID-F9183C70-2E96-40F4-9104-F3814A5A331F) or [homebrew](https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac)).
I would rather not override the user set `JAVA_HOME` in those cases.
I believe there are two options:
- Require an installation of any JDK which also sets `JAVA_HOME`
- Add the default path described in Java 8 & 9 install instructions before `java -jar...` if just `java` is not found

**Comment by the-matzup** [comment]
When will a new version of OpenRoberta Connector be released that contains the bugfix? I'm a teacher and currently many of my students need a solution.

**Comment by boonto** [comment]
The default Java path as described by Oracle is now used when Java is not found on the PATH.

**Comment by the-matzup** [comment]
Thanks 👍

**Comment by the-matzup** [comment]
Leider muss ich den Bug nochmal öffnen. Nachdem mir einige Schüler rückgemeldet hatte, dass es mit der neuen Version (1.2.1) immer noch nicht geht, habe ich mir den neuen Skript nochmal angeschaut. 

In der if-Abfrage gibt es einen Fehler, wodurch diese nicht wahr wird:
`if ! hash java 2>/dev/null`

Die Befehlszeile innerhalb der if-Abfrage funktioniert und damit würde das Java-Problem behoben sein:
`JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/`

**Comment by boonto** [comment]
That should be correct, `if hash java 2>/dev/null` returns true when the command `java` can be found.
Then, with the `!` negation it runs the `then` part when java doesn't exist.

You should be able to test it with `if ! hash java 2>/dev/null; then echo hello; fi` which does not print `echo` as java is on my path, but `if ! hash programthatsnotonpath 2>/dev/null; then echo hello; fi` prints hello as that command cannot be found.
