### ISSUE TITLE
Implementation of the Lego Spike Prime/Robot Inventor (Big Hub) in the connector program

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-connector#38]
The Lego Spike Prime/Robot Inventor (Big Hub) should be implemented in the openroberta-connector program, so that it is possible to connect the robot with the openroberta-lab and upload programs from the openroberta-lab onto the robot.

- [x] connector program discovers robot
- [x] openroberta-lab connection works
- [x] program upload works

**Comment by rbudde** [comment]
released
