### ISSUE TITLE
Calliope mini detected but does not connect to server

### ISSUE THREAD

**Issue by cweiske** [OpenRoberta/openroberta-connector#40]
When I understand the [connector wiki page](https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Open+Roberta+Connector) correctly, it should work as follows:

1. start connector
2. connector finds Calliope mini
3. A token (code) is shown that I have to enter in lab.openroberta.org
4. When I click "run" on lab.openroberta.org, it should send the program to the connector, and the connector should store it on the calliope

This does not work with a `J-Link OB-CALLIOPE-MINI V2.1`. Here it is as follows:

1. start connector. The connection image between the PC and the robot is flashing, switching between USB and wireless icons
2. I attach the calliope via USB
3. connector finds Calliope mini and shows "Found robots: Micro:bit/Calliope mini", and the connection icon only shows the USB icon (flashes only every ~10 seconds now, no wireless icon anymore). The server connection icon is flashing. The "connect" button text changes to "disconnect".
5. No token is shown
6. The connector shows a message that I can send programs to the robot now.

![2022-11-10 openroberta connector calliope](https://user-images.githubusercontent.com/59036/201190304-8f1ffcf1-fd28-42d2-9e2a-1e1a673b8f9d.png)

Since I never got a token, I don't know how lab.openroberta.org should know how to connect back to my PC.

What am I doing wrong? How should the process be?

----
This is with connector 1.5.0 on both Linux and MacOS.

**Comment by bjost2s** [comment]
When working with calliope/microbit you should follow the instructions in the [Open Roberta Wiki](https://wiki.open-roberta.org). The connector program is only needed if you want to use the serial monitor, but you can also use any other serial monitor.

**Comment by cweiske** [comment]
So it is not possible to use the connector to let lab.openroberta.org store files onto the calliope without using the browser-file-download?

I had hoped that using the OpenRoberta connector would speed up the testing process. Using the browser file download requires me to change either the download folder just for programming, or manually select the calliope folder every time when running the program.

**Comment by bjost2s** [comment]
You are right, but you can speed up the browser download twice:

- change the download folder, if no calliope is attached you might find your downloads in "Downloads"
- check once in a session "Ok, ich habe meinen ...": you only have to click once on the "run" button and the system is doing the rest
![image](https://user-images.githubusercontent.com/1613069/204354169-878258c9-bb60-4d7e-b7d2-18a16263f713.png)

**Comment by cweiske** [comment]
I am aware of this, which is why I wrote:
>  Using the browser file download requires me to change either the download folder just for programming

Do you plan to add connector support for such program-through-downloading devices like Calliope?

**Comment by bjost2s** [comment]
No, sorry, there is no plan to support this feature
