### ISSUE TITLE
More User-Friendly Serial Monitor

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-connector#42]
Currently the serial monitor of an embedded device (if it exists) must be restarted every time a program is uploaded to the device.
This can be done by the connector program (which knows, that it must be done, because it uploads the program).

We must be careful, there may be timing problems.

**Comment by RaghuvirShirodkar** [comment]
Tested source code on `openroberta-connector`. Serial monitor is restarted when state is `WAIT_FOR_CMD`, which is the case when a program is uploaded to the device.
Function definition can be [found here](https://github.com/OpenRoberta/openroberta-connector/blob/5a205dceea031e5f19c119e90ab17ae388b47add/src/main/java/de/fhg/iais/roberta/ui/serialMonitor/SerialMonitorController.java#L49).

**Comment by RaghuvirShirodkar** [comment]
Tested on mBot2 and Arduino Uno with latest release of Open Roberta Connector app (v1.6.3). Serial monitor in Open Roberta Connector app works as expected. 
**Note**: v1.6.**3** still has the `pre-release` tag, while v1.6.2 has the `latest` tag. v1.6.3 should be tagged as `latest` instead.


![Released versions](https://user-images.githubusercontent.com/43172112/224977731-7cf1b010-d8ac-4289-af9b-201a60e0cd7e.png)
